{
 "title": "Cart Service Exemplars",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows the use of metric exemplars.\nExemplars can be used to look up a trace in Jaeger.\nOnly the most recent exemplars may still be available in Jaeger.\n<br>\nChart panels may require 5 minutes after the Demo is started before rendering data."
   }
  },
  {
   "title": "GetCart Exemplars",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "GetCart Latency Heatmap with Exemplars",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by(le) (rate(traces_span_metrics_duration_milliseconds_bucket[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "95th Pct Cart GetCart Latency with Exemplars",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(traces_span_metrics_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "p95 GetCart"
      }
     ]
    }
   ]
  },
  { "title": "AddItem Exemplars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "加入購物車請求量統計",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(app_cart_add_item_latency_seconds_count{}[1h])",
     "legendFormat": "1小時內"
    },
    {
     "expr": "increase(app_cart_add_item_latency_seconds_count{}[12h])",
     "legendFormat": "12小時內"
    }
   ]
  },
  {
   "title": "購物車請求延遲 (P50)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, \n  sum(\n    traces_span_metrics_duration_milliseconds_bucket{\n      service_name=\"cart\", \n      span_name=\"POST /oteldemo.CartService/AddItem\"\n    }\n  ) by (le, span_name)\n)",
     "legendFormat": "AddItem"
    }
   ]
  },
  {
   "title": "購物車請求延遲 (P99)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(\n    traces_span_metrics_duration_milliseconds_bucket{\n      service_name=\"cart\", \n      span_name=\"POST /oteldemo.CartService/AddItem\"\n    }\n  ) by (le, span_name)\n)",
     "legendFormat": "AddItem"
    }
   ]
  },
  {
   "title": "購物車請求延遲 (P50) 的對比",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, \n  sum(\n    traces_span_metrics_duration_milliseconds_bucket{\n      service_name=\"cart\", \n      span_name=\"POST /oteldemo.CartService/AddItem\"\n    }\n  ) by (le, span_name)\n)",
     "legendFormat": "AddItem"
    },
    {
     "expr": "histogram_quantile(0.99, \n  sum(\n    traces_span_metrics_duration_milliseconds_bucket{\n      service_name=\"cart\", \n      span_name=\"POST /oteldemo.CartService/AddItem\"\n    } offset 1h\n  ) by (le, span_name)\n)",
     "legendFormat": "AddItem 1h before"
    }
   ]
  },
  {
   "title": "購物車請求成功率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100* (1 - (sum(rate(traces_span_metrics_calls_total{status_code=\"STATUS_CODE_ERROR\", service_name=\"cart\"}[$__rate_interval])) / sum(rate(traces_span_metrics_calls_total{service_name=\"cart\"}[$__rate_interval]))) ) or vector(100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AddItem Latency Heatmap with Exemplars",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(le) (rate(app_cart_add_item_latency_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "95th Pct Cart AddItem Latency with Exemplars",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_cart_add_item_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p95 AddItem"
    }
   ]
  }
 ]
}